/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SocialMedia = IDL.Record({ 'instagram' : IDL.Text });
export const BusinessProfile = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'socialMedia' : SocialMedia,
});

export const idlService = IDL.Service({
  'getBusinessInfo' : IDL.Func([], [BusinessProfile], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SocialMedia = IDL.Record({ 'instagram' : IDL.Text });
  const BusinessProfile = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'socialMedia' : SocialMedia,
  });
  
  return IDL.Service({
    'getBusinessInfo' : IDL.Func([], [BusinessProfile], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };